# This is a basic workflow to help you get started with Actions

name: Check

on:
  [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '18'
    - run: yarn install
    - name: Lint
      run: yarn lint
    - name: Build
      run: yarn build
